version: 2

jobs:
  build_recipe:
    machine: true
    environment:
      MINICONDA_FILE: "Miniconda3-latest-Linux-x86_64.sh"
    steps:
      - run: bash -c "echo"

workflows:
  version: 2
  build_recipe_and_no_recipe:
    jobs:
      - build_recipe
